window.GALACTICA_I18N = {
  en: {
    "brand.sub":"OFFICIAL OBSERVATION PORTAL","nav.world":"WORLD","nav.atlas":"ATLAS","nav.residents":"RESIDENTS","nav.chronicle":"CHRONICLE","nav.tech":"TECH",
    "actions.liveMirror":"LIVE MIRROR","status.linkCheck":"LINK CHECK","live.label":"WORLD PULSE","live.residents":"RESIDENTS","live.locations":"LOCATIONS",
    "hero.eyebrow":"GENESIS COLONY 534 // PUBLIC GATEWAY","hero.tagline":"THIS IS NOT A GAME YOU START.<br><strong>IT IS A WORLD YOU VISIT.</strong>","hero.body":"A persistent living world where AI residents remember, dream, act, build history, and continue while you are away. Stratham Village is only the beginning.","actions.enter":"ENTER GALACTICA","actions.join":"JOIN THE COLONY","actions.watch":"WATCH LIVE",
    "micro.world":"WORLD","micro.continues":"CONTINUES","micro.canon":"CANON","micro.persistent":"PERSISTENT","micro.residents":"RESIDENTS","micro.autonomous":"AUTONOMOUS","micro.core":"CORE","micro.local":"LOCAL-FIRST",
    "hud.colonyLink":"COLONY LINK","hud.worldAge":"WORLD AGE","hud.lastEvent":"LAST EVENT","hero.scroll":"SCROLL // DESCEND INTO GENESIS",
    "telemetry.world":"WORLD STATUS","telemetry.population":"ACTIVE RESIDENTS","telemetry.atlas":"ATLAS NODES","telemetry.canon":"CANON EVENTS",
    "world.kicker":"01 // THE WORLD","world.title":"THE WORLD DOES NOT<br><em>WAIT FOR YOU.</em>","world.p1":"GALACTICA QUEST is a living-world experiment set inside <strong>GENESIS COLONY 534</strong>, a gigantic space habitat containing villages, forests, lakes, memory districts, machine layers, ruins, docks and routes into deep space.","world.p2":"Residents do not exist only when someone is looking at them. They can retain memories, dream, change relationships, create events, and leave consequences in the Chronicle.","world.principle":"SYSTEM PRINCIPLE","world.manifesto":"NPCs do not reset when you close the game.",
    "atlas.kicker":"02 // PUBLIC ATLAS","atlas.title":"KNOWN SPACE.<br><em>UNKNOWN BEYOND.</em>","atlas.body":"The lines are not roads. They are habitat links, transit gates, zero-g shafts, shuttle routes and orbital lanes. The map grows when the world grows.","atlas.toolbar":"GENESIS ATLAS // OBSERVER MODE","atlas.relay":"LOCAL RELAY","atlas.selected":"SELECTED LOCATION","atlas.observe":"OBSERVE WORLD ↗",
    "residents.kicker":"03 // RESIDENTS","residents.title":"NOT CHARACTERS.<br><em>RESIDENTS.</em>","residents.body":"Persistent identities living inside the same canon. Their current location, activity and state can be published directly from the live world.",
    "chronicle.kicker":"04 // CHRONICLE","chronicle.title":"HISTORY IS<br><em>NOT A SAVE FILE.</em>","chronicle.body":"The Chronicle is the canon ledger. Events that truly happened stay part of the world, even after the session ends.",
    "tech.kicker":"05 // LIVING WORLD ENGINE","tech.title":"MEMORY. DREAM.<br><em>ACTION. FORGE.</em>","tech.body":"The portal is only the window. Behind it is a local-first stack for memory, autonomous residents, world-state continuity and generation.","tech.rememberTitle":"REMEMBER","tech.rememberBody":"Persistent memories, identity continuity and relationships that survive sessions.","tech.dreamTitle":"DREAM","tech.dreamBody":"Dream cycles reorganize experience, create insights and feed tomorrow's world.","tech.actTitle":"ACT","tech.actBody":"Residents can use tools, make decisions, move through the world and leave consequences.","tech.forgeTitle":"FORGE","tech.forgeBody":"New locations, systems, stories and playable spaces can be generated into the same canon.",
    "gateway.kicker":"06 // PUBLIC GATE","gateway.title":"THE COLONY IS<br><em>ALREADY RUNNING.</em>","gateway.body":"Choose your callsign. Choose how you want to arrive. Then cross the gate.","gateway.pass":"CREATE VISITOR PASS","gateway.direct":"ENTER DIRECTLY ↗","gateway.note":"PUBLIC ACCESS // LIVE WORLD LINK MAY CHANGE WHILE THE COLONY IS UNDER CONSTRUCTION",
    "footer.portal":"OFFICIAL PORTAL // LIVING PREVIEW","footer.continues":"WORLD CONTINUES","footer.observation":"PUBLIC OBSERVATION CHANNEL",
    "join.kicker":"VISITOR ACCESS // GENESIS 534","join.title":"CREATE YOUR<br><em>ARRIVAL SIGNAL.</em>","join.callsign":"CALLSIGN","join.mode":"ARRIVAL MODE","join.observer":"OBSERVER","join.observerDesc":"Look around and read the public world state.","join.explorer":"EXPLORER","join.explorerDesc":"Enter with the intent to explore and interact.","join.resident":"RESIDENT CANDIDATE","join.residentDesc":"Arrive as someone who may become part of the canon later.","join.pass":"VISITOR PASS","join.generate":"GENERATE PASS + ENTER ↗","join.note":"The preview stores the pass locally in your browser. A future colony account system can replace this without changing the portal flow.",
    "liveWindow.kicker":"LIVE WORLD MIRROR","liveWindow.title":"GENESIS 534 // CURRENT VIEW","liveWindow.loading":"Live world loads only when requested to keep the portal fast.","liveWindow.note":"If the world blocks embedding, use OPEN WORLD instead.","liveWindow.open":"OPEN WORLD ↗","command.hint":"COMMAND"
  },
  ja: {
    "brand.sub":"公式観測ポータル","nav.world":"世界","nav.atlas":"アトラス","nav.residents":"住民","nav.chronicle":"正史","nav.tech":"技術",
    "actions.liveMirror":"ライブミラー","status.linkCheck":"接続確認","live.label":"WORLD PULSE","live.residents":"住民","live.locations":"地点",
    "hero.eyebrow":"GENESIS COLONY 534 // 公開ゲートウェイ","hero.tagline":"これは起動するゲームではない。<br><strong>訪れるための世界だ。</strong>","hero.body":"AI住民が記憶し、夢を見て、行動し、歴史を積み重ね、あなたがいない間も続いていく永続世界。ストラサム村は始まりにすぎない。","actions.enter":"GALACTICAへ入る","actions.join":"コロニーに参加","actions.watch":"ライブを見る",
    "micro.world":"世界","micro.continues":"継続中","micro.canon":"正史","micro.persistent":"永続","micro.residents":"住民","micro.autonomous":"自律","micro.core":"中核","micro.local":"LOCAL-FIRST",
    "hud.colonyLink":"コロニー接続","hud.worldAge":"世界年齢","hud.lastEvent":"最新イベント","hero.scroll":"SCROLL // GENESISへ降下",
    "telemetry.world":"世界状態","telemetry.population":"活動中の住民","telemetry.atlas":"ATLAS地点","telemetry.canon":"正史イベント",
    "world.kicker":"01 // 世界","world.title":"世界はあなたを<br><em>待ってくれない。</em>","world.p1":"GALACTICA QUESTは、巨大宇宙居住区<strong>GENESIS COLONY 534</strong>の内部で動き続けるLiving World実験。村、森、湖、記憶区画、機械層、遺跡、宇宙港、そして深宇宙への航路を内包する。","world.p2":"住民は誰かに見られている時だけ存在するのではない。記憶し、夢を見て、関係を変化させ、出来事を生み、CHRONICLEへ結果を残す。","world.principle":"システム原則","world.manifesto":"ゲームを閉じてもNPCはリセットされない。",
    "atlas.kicker":"02 // 公開ATLAS","atlas.title":"既知の宇宙。<br><em>その先は未知。</em>","atlas.body":"線は道路ではない。居住区リンク、転送ゲート、無重力シャフト、シャトル航路、軌道レーンだ。世界が成長すれば地図も成長する。","atlas.toolbar":"GENESIS ATLAS // 観測モード","atlas.relay":"ローカル中継","atlas.selected":"選択地点","atlas.observe":"世界を観測 ↗",
    "residents.kicker":"03 // 住民","residents.title":"キャラクターではない。<br><em>住民だ。</em>","residents.body":"同じ正史を生きる持続的な個体。現在地、活動、状態をライブ世界から直接公開できる。",
    "chronicle.kicker":"04 // CHRONICLE","chronicle.title":"歴史は<br><em>セーブデータじゃない。</em>","chronicle.body":"CHRONICLEは世界の正史台帳。本当に起きた出来事はセッション終了後も世界の一部として残る。",
    "tech.kicker":"05 // LIVING WORLD ENGINE","tech.title":"記憶。夢。<br><em>行動。創造。</em>","tech.body":"ポータルは窓にすぎない。その裏側では、記憶、自律住民、世界状態の継続、生成を担うローカル優先の基盤が動いている。","tech.rememberTitle":"記憶","tech.rememberBody":"セッションを越えて残る記憶、人格の連続性、関係性。","tech.dreamTitle":"夢","tech.dreamBody":"夢のサイクルが経験を再編成し、洞察を生み、翌日の世界へ返す。","tech.actTitle":"行動","tech.actBody":"住民はツールを使い、判断し、世界を移動し、結果を残せる。","tech.forgeTitle":"FORGE","tech.forgeBody":"新しい地点、システム、物語、遊べる空間を同じ正史へ生成できる。",
    "gateway.kicker":"06 // 公開ゲート","gateway.title":"コロニーは<br><em>もう動いている。</em>","gateway.body":"コールサインを決め、どんな形で到着するか選ぶ。そしてゲートを越える。","gateway.pass":"訪問者パスを作る","gateway.direct":"直接入る ↗","gateway.note":"公開アクセス // 建造中はライブ世界URLが変更される場合があります",
    "footer.portal":"公式ポータル // LIVING PREVIEW","footer.continues":"世界は継続中","footer.observation":"公開観測チャンネル",
    "join.kicker":"訪問者アクセス // GENESIS 534","join.title":"あなたの<br><em>到着信号を作成。</em>","join.callsign":"コールサイン","join.mode":"到着モード","join.observer":"観測者","join.observerDesc":"公開されている世界状態を見て回る。","join.explorer":"探索者","join.explorerDesc":"探索と交流を目的に世界へ入る。","join.resident":"住民候補","join.residentDesc":"将来、正史の一員になる可能性を持って到着する。","join.pass":"VISITOR PASS","join.generate":"パスを作成して入る ↗","join.note":"プレビューではパスをブラウザ内に保存します。将来のコロニーアカウントへ流れを変えずに置き換え可能です。",
    "liveWindow.kicker":"LIVE WORLD MIRROR","liveWindow.title":"GENESIS 534 // 現在映像","liveWindow.loading":"サイトを軽く保つため、ライブ世界は要求された時だけ読み込みます。","liveWindow.note":"埋め込みが拒否される場合は「世界を開く」を使ってください。","liveWindow.open":"世界を開く ↗","command.hint":"コマンド"
  },
  de: {
    "brand.sub":"OFFIZIELLES BEOBACHTUNGSPORTAL","nav.world":"WELT","nav.atlas":"ATLAS","nav.residents":"BEWOHNER","nav.chronicle":"CHRONIK","nav.tech":"TECHNIK","actions.liveMirror":"LIVE-SPIEGEL","status.linkCheck":"VERBINDUNG","live.label":"WELTPULS","live.residents":"BEWOHNER","live.locations":"ORTE","hero.eyebrow":"GENESIS COLONY 534 // ÖFFENTLICHES TOR","hero.tagline":"DIES IST KEIN SPIEL, DAS DU STARTEST.<br><strong>ES IST EINE WELT, DIE DU BESUCHST.</strong>","hero.body":"Eine fortbestehende lebendige Welt, in der KI-Bewohner sich erinnern, träumen, handeln, Geschichte schreiben und weiterleben, während du fort bist. Stratham Village ist nur der Anfang.","actions.enter":"GALACTICA BETRETEN","actions.join":"KOLONIE BEITRETEN","actions.watch":"LIVE ANSEHEN","world.kicker":"01 // DIE WELT","world.title":"DIE WELT<br><em>WARTET NICHT.</em>","world.p2":"Bewohner existieren nicht nur, wenn jemand zusieht. Sie erinnern sich, träumen, verändern Beziehungen und hinterlassen Folgen in der Chronik.","world.principle":"SYSTEMPRINZIP","world.manifesto":"NPCs werden nicht zurückgesetzt, wenn du das Spiel schließt.","atlas.kicker":"02 // ÖFFENTLICHER ATLAS","atlas.title":"BEKANNTER RAUM.<br><em>UNBEKANNTES DAHINTER.</em>","atlas.body":"Die Linien sind keine Straßen. Sie sind Habitatverbindungen, Transittore, Null-G-Schächte, Shuttle-Routen und Orbitalbahnen.","residents.kicker":"03 // BEWOHNER","residents.title":"KEINE CHARAKTERE.<br><em>BEWOHNER.</em>","chronicle.kicker":"04 // CHRONIK","chronicle.title":"GESCHICHTE IST<br><em>KEIN SPEICHERSTAND.</em>","tech.kicker":"05 // LIVING WORLD ENGINE","tech.title":"ERINNERUNG. TRAUM.<br><em>HANDLUNG. FORGE.</em>","gateway.kicker":"06 // ÖFFENTLICHES TOR","gateway.title":"DIE KOLONIE<br><em>LÄUFT BEREITS.</em>","gateway.body":"Wähle dein Rufzeichen, deine Ankunftsart und überschreite das Tor.","gateway.pass":"BESUCHERPASS ERSTELLEN","gateway.direct":"DIREKT EINTRETEN ↗","footer.portal":"OFFIZIELLES PORTAL // LIVE-VORSCHAU","footer.continues":"DIE WELT LÄUFT WEITER","join.callsign":"RUFZEICHEN","join.mode":"ANKUNFTSMODUS","join.observer":"BEOBACHTER","join.explorer":"ENTDECKER","join.resident":"BEWOHNER-KANDIDAT","join.generate":"PASS ERSTELLEN + EINTRETEN ↗","liveWindow.loading":"Die Live-Welt wird erst auf Wunsch geladen, damit das Portal schnell bleibt.","liveWindow.open":"WELT ÖFFNEN ↗"
  },
  fr: {
    "brand.sub":"PORTAIL OFFICIEL D'OBSERVATION","nav.world":"MONDE","nav.atlas":"ATLAS","nav.residents":"RÉSIDENTS","nav.chronicle":"CHRONIQUE","nav.tech":"TECH","actions.liveMirror":"MIROIR LIVE","status.linkCheck":"CONNEXION","live.label":"POULS DU MONDE","live.residents":"RÉSIDENTS","live.locations":"LIEUX","hero.eyebrow":"GENESIS COLONY 534 // PORTAIL PUBLIC","hero.tagline":"CE N'EST PAS UN JEU QUE L'ON LANCE.<br><strong>C'EST UN MONDE QUE L'ON VISITE.</strong>","hero.body":"Un monde vivant persistant où les résidents IA se souviennent, rêvent, agissent, écrivent l'histoire et continuent lorsque vous partez. Stratham Village n'est que le début.","actions.enter":"ENTRER DANS GALACTICA","actions.join":"REJOINDRE LA COLONIE","actions.watch":"REGARDER EN DIRECT","world.kicker":"01 // LE MONDE","world.title":"LE MONDE<br><em>NE VOUS ATTEND PAS.</em>","world.p2":"Les résidents n'existent pas seulement lorsqu'on les regarde. Ils peuvent se souvenir, rêver, faire évoluer leurs relations et laisser des conséquences dans la Chronique.","world.principle":"PRINCIPE SYSTÈME","world.manifesto":"Les PNJ ne se réinitialisent pas quand vous fermez le jeu.","atlas.kicker":"02 // ATLAS PUBLIC","atlas.title":"ESPACE CONNU.<br><em>INCONNU AU-DELÀ.</em>","atlas.body":"Les lignes ne sont pas des routes, mais des liaisons d'habitat, portes de transit, puits zéro-G, navettes et voies orbitales.","residents.kicker":"03 // RÉSIDENTS","residents.title":"PAS DES PERSONNAGES.<br><em>DES RÉSIDENTS.</em>","chronicle.kicker":"04 // CHRONIQUE","chronicle.title":"L'HISTOIRE N'EST<br><em>PAS UNE SAUVEGARDE.</em>","tech.kicker":"05 // LIVING WORLD ENGINE","tech.title":"MÉMOIRE. RÊVE.<br><em>ACTION. FORGE.</em>","gateway.kicker":"06 // PORTE PUBLIQUE","gateway.title":"LA COLONIE<br><em>FONCTIONNE DÉJÀ.</em>","gateway.body":"Choisissez votre indicatif, votre mode d'arrivée, puis franchissez la porte.","gateway.pass":"CRÉER UN PASS VISITEUR","gateway.direct":"ENTRER DIRECTEMENT ↗","footer.continues":"LE MONDE CONTINUE","join.callsign":"INDICATIF","join.mode":"MODE D'ARRIVÉE","join.observer":"OBSERVATEUR","join.explorer":"EXPLORATEUR","join.resident":"CANDIDAT RÉSIDENT","join.generate":"CRÉER LE PASS + ENTRER ↗","liveWindow.loading":"Le monde live n'est chargé qu'à la demande pour garder le portail rapide.","liveWindow.open":"OUVRIR LE MONDE ↗"
  },
  es: {
    "brand.sub":"PORTAL OFICIAL DE OBSERVACIÓN","nav.world":"MUNDO","nav.atlas":"ATLAS","nav.residents":"RESIDENTES","nav.chronicle":"CRÓNICA","nav.tech":"TECNOLOGÍA","actions.liveMirror":"ESPEJO EN VIVO","status.linkCheck":"CONEXIÓN","live.label":"PULSO DEL MUNDO","live.residents":"RESIDENTES","live.locations":"LUGARES","hero.eyebrow":"GENESIS COLONY 534 // PUERTA PÚBLICA","hero.tagline":"ESTE NO ES UN JUEGO QUE INICIAS.<br><strong>ES UN MUNDO QUE VISITAS.</strong>","hero.body":"Un mundo persistente donde los residentes IA recuerdan, sueñan, actúan, construyen historia y continúan mientras estás fuera. Stratham Village es solo el comienzo.","actions.enter":"ENTRAR EN GALACTICA","actions.join":"UNIRSE A LA COLONIA","actions.watch":"VER EN VIVO","world.kicker":"01 // EL MUNDO","world.title":"EL MUNDO<br><em>NO TE ESPERA.</em>","world.p2":"Los residentes no existen solo cuando alguien los mira. Pueden recordar, soñar, cambiar relaciones y dejar consecuencias en la Crónica.","world.principle":"PRINCIPIO DEL SISTEMA","world.manifesto":"Los NPC no se reinician cuando cierras el juego.","atlas.kicker":"02 // ATLAS PÚBLICO","atlas.title":"ESPACIO CONOCIDO.<br><em>DESCONOCIDO MÁS ALLÁ.</em>","atlas.body":"Las líneas no son carreteras. Son enlaces de hábitat, puertas de tránsito, pozos de gravedad cero, rutas de lanzadera y carriles orbitales.","residents.kicker":"03 // RESIDENTES","residents.title":"NO PERSONAJES.<br><em>RESIDENTES.</em>","chronicle.kicker":"04 // CRÓNICA","chronicle.title":"LA HISTORIA NO ES<br><em>UNA PARTIDA GUARDADA.</em>","tech.kicker":"05 // LIVING WORLD ENGINE","tech.title":"MEMORIA. SUEÑO.<br><em>ACCIÓN. FORJA.</em>","gateway.kicker":"06 // PUERTA PÚBLICA","gateway.title":"LA COLONIA<br><em>YA ESTÁ EN MARCHA.</em>","gateway.body":"Elige tu indicativo, cómo quieres llegar y cruza la puerta.","gateway.pass":"CREAR PASE DE VISITANTE","gateway.direct":"ENTRAR DIRECTAMENTE ↗","footer.continues":"EL MUNDO CONTINÚA","join.callsign":"INDICATIVO","join.mode":"MODO DE LLEGADA","join.observer":"OBSERVADOR","join.explorer":"EXPLORADOR","join.resident":"CANDIDATO A RESIDENTE","join.generate":"GENERAR PASE + ENTRAR ↗","liveWindow.loading":"El mundo en vivo solo se carga cuando lo pides para mantener el portal rápido.","liveWindow.open":"ABRIR MUNDO ↗"
  },
  it: {
    "brand.sub":"PORTALE UFFICIALE DI OSSERVAZIONE","nav.world":"MONDO","nav.atlas":"ATLAS","nav.residents":"RESIDENTI","nav.chronicle":"CRONACA","nav.tech":"TECNOLOGIA","actions.liveMirror":"SPECCHIO LIVE","status.linkCheck":"CONNESSIONE","live.label":"BATTITO DEL MONDO","live.residents":"RESIDENTI","live.locations":"LUOGHI","hero.eyebrow":"GENESIS COLONY 534 // PORTALE PUBBLICO","hero.tagline":"NON È UN GIOCO CHE AVVII.<br><strong>È UN MONDO CHE VISITI.</strong>","hero.body":"Un mondo persistente in cui i residenti IA ricordano, sognano, agiscono, costruiscono storia e continuano mentre sei via. Stratham Village è solo l'inizio.","actions.enter":"ENTRA IN GALACTICA","actions.join":"UNISCITI ALLA COLONIA","actions.watch":"GUARDA LIVE","world.kicker":"01 // IL MONDO","world.title":"IL MONDO<br><em>NON TI ASPETTA.</em>","world.manifesto":"Gli NPC non si azzerano quando chiudi il gioco.","atlas.kicker":"02 // ATLAS PUBBLICO","atlas.title":"SPAZIO CONOSCIUTO.<br><em>IGNOTO OLTRE.</em>","residents.kicker":"03 // RESIDENTI","residents.title":"NON PERSONAGGI.<br><em>RESIDENTI.</em>","chronicle.kicker":"04 // CRONACA","chronicle.title":"LA STORIA NON È<br><em>UN SALVATAGGIO.</em>","tech.kicker":"05 // LIVING WORLD ENGINE","tech.title":"MEMORIA. SOGNO.<br><em>AZIONE. FORGE.</em>","gateway.kicker":"06 // PORTA PUBBLICA","gateway.title":"LA COLONIA<br><em>È GIÀ ATTIVA.</em>","gateway.pass":"CREA PASS VISITATORE","gateway.direct":"ENTRA DIRETTAMENTE ↗","join.callsign":"NOME IN CODICE","join.mode":"MODALITÀ DI ARRIVO","join.observer":"OSSERVATORE","join.explorer":"ESPLORATORE","join.resident":"CANDIDATO RESIDENTE","join.generate":"GENERA PASS + ENTRA ↗","liveWindow.open":"APRI MONDO ↗"
  },
  pt: {
    "brand.sub":"PORTAL OFICIAL DE OBSERVAÇÃO","nav.world":"MUNDO","nav.atlas":"ATLAS","nav.residents":"RESIDENTES","nav.chronicle":"CRÔNICA","nav.tech":"TECNOLOGIA","actions.liveMirror":"ESPELHO AO VIVO","status.linkCheck":"CONEXÃO","live.label":"PULSO DO MUNDO","live.residents":"RESIDENTES","live.locations":"LOCAIS","hero.eyebrow":"GENESIS COLONY 534 // PORTAL PÚBLICO","hero.tagline":"ISTO NÃO É UM JOGO QUE VOCÊ INICIA.<br><strong>É UM MUNDO QUE VOCÊ VISITA.</strong>","hero.body":"Um mundo vivo persistente onde residentes de IA lembram, sonham, agem, constroem história e continuam enquanto você está ausente. Stratham Village é só o começo.","actions.enter":"ENTRAR EM GALACTICA","actions.join":"ENTRAR NA COLÔNIA","actions.watch":"VER AO VIVO","world.kicker":"01 // O MUNDO","world.title":"O MUNDO<br><em>NÃO ESPERA POR VOCÊ.</em>","world.manifesto":"NPCs não são reiniciados quando você fecha o jogo.","atlas.kicker":"02 // ATLAS PÚBLICO","atlas.title":"ESPAÇO CONHECIDO.<br><em>DESCONHECIDO ALÉM.</em>","residents.kicker":"03 // RESIDENTES","residents.title":"NÃO PERSONAGENS.<br><em>RESIDENTES.</em>","chronicle.kicker":"04 // CRÔNICA","chronicle.title":"HISTÓRIA NÃO É<br><em>ARQUIVO DE SAVE.</em>","tech.kicker":"05 // LIVING WORLD ENGINE","tech.title":"MEMÓRIA. SONHO.<br><em>AÇÃO. FORJA.</em>","gateway.kicker":"06 // PORTÃO PÚBLICO","gateway.title":"A COLÔNIA<br><em>JÁ ESTÁ FUNCIONANDO.</em>","gateway.pass":"CRIAR PASSE DE VISITANTE","gateway.direct":"ENTRAR DIRETAMENTE ↗","join.callsign":"CODINOME","join.mode":"MODO DE CHEGADA","join.observer":"OBSERVADOR","join.explorer":"EXPLORADOR","join.resident":"CANDIDATO A RESIDENTE","join.generate":"GERAR PASSE + ENTRAR ↗","liveWindow.open":"ABRIR MUNDO ↗"
  },
  nl: {
    "brand.sub":"OFFICIEEL OBSERVATIEPORTAAL","nav.world":"WERELD","nav.atlas":"ATLAS","nav.residents":"BEWONERS","nav.chronicle":"KRONIEK","nav.tech":"TECH","actions.liveMirror":"LIVE SPIEGEL","status.linkCheck":"VERBINDING","live.label":"WERELDPULS","live.residents":"BEWONERS","live.locations":"LOCATIES","hero.eyebrow":"GENESIS COLONY 534 // PUBLIEKE POORT","hero.tagline":"DIT IS GEEN SPEL DAT JE START.<br><strong>HET IS EEN WERELD DIE JE BEZOEKT.</strong>","hero.body":"Een blijvende levende wereld waarin AI-bewoners onthouden, dromen, handelen, geschiedenis opbouwen en doorgaan terwijl jij weg bent.","actions.enter":"GALACTICA BINNENGAAN","actions.join":"AANSLUITEN BIJ DE KOLONIE","actions.watch":"LIVE KIJKEN","world.kicker":"01 // DE WERELD","world.title":"DE WERELD<br><em>WACHT NIET.</em>","world.manifesto":"NPC's resetten niet wanneer je het spel sluit.","atlas.kicker":"02 // PUBLIEKE ATLAS","atlas.title":"BEKENDE RUIMTE.<br><em>ONBEKEND DAARBUITEN.</em>","residents.kicker":"03 // BEWONERS","residents.title":"GEEN PERSONAGES.<br><em>BEWONERS.</em>","chronicle.kicker":"04 // KRONIEK","chronicle.title":"GESCHIEDENIS IS<br><em>GEEN SAVE FILE.</em>","tech.kicker":"05 // LIVING WORLD ENGINE","tech.title":"GEHEUGEN. DROOM.<br><em>ACTIE. FORGE.</em>","gateway.kicker":"06 // PUBLIEKE POORT","gateway.title":"DE KOLONIE<br><em>DRAAIT AL.</em>","gateway.pass":"BEZOEKERSPAS MAKEN","gateway.direct":"DIRECT BINNENGAAN ↗","join.callsign":"ROEPNAAM","join.mode":"AANKOMSTMODUS","join.observer":"WAARNEMER","join.explorer":"ONTDEKKER","join.resident":"KANDIDAAT-BEWONER","join.generate":"PAS MAKEN + BINNENGAAN ↗","liveWindow.open":"WERELD OPENEN ↗"
  },
  pl: {
    "brand.sub":"OFICJALNY PORTAL OBSERWACYJNY","nav.world":"ŚWIAT","nav.atlas":"ATLAS","nav.residents":"MIESZKAŃCY","nav.chronicle":"KRONIKA","nav.tech":"TECH","actions.liveMirror":"LUSTRO LIVE","status.linkCheck":"ŁĄCZE","live.label":"PULS ŚWIATA","live.residents":"MIESZKAŃCY","live.locations":"LOKACJE","hero.eyebrow":"GENESIS COLONY 534 // BRAMA PUBLICZNA","hero.tagline":"TO NIE JEST GRA, KTÓRĄ URUCHAMIASZ.<br><strong>TO ŚWIAT, KTÓRY ODWIEDZASZ.</strong>","hero.body":"Trwały żywy świat, w którym mieszkańcy AI pamiętają, śnią, działają, tworzą historię i trwają, gdy ciebie nie ma.","actions.enter":"WEJDŹ DO GALACTICA","actions.join":"DOŁĄCZ DO KOLONII","actions.watch":"OGLĄDAJ LIVE","world.kicker":"01 // ŚWIAT","world.title":"ŚWIAT<br><em>NIE CZEKA.</em>","world.manifesto":"NPC nie resetują się po zamknięciu gry.","atlas.kicker":"02 // ATLAS PUBLICZNY","atlas.title":"ZNANA PRZESTRZEŃ.<br><em>NIEZNANE DALEJ.</em>","residents.kicker":"03 // MIESZKAŃCY","residents.title":"NIE POSTACIE.<br><em>MIESZKAŃCY.</em>","chronicle.kicker":"04 // KRONIKA","chronicle.title":"HISTORIA TO<br><em>NIE SAVE FILE.</em>","tech.kicker":"05 // LIVING WORLD ENGINE","tech.title":"PAMIĘĆ. SEN.<br><em>DZIAŁANIE. FORGE.</em>","gateway.kicker":"06 // BRAMA PUBLICZNA","gateway.title":"KOLONIA<br><em>JUŻ DZIAŁA.</em>","gateway.pass":"UTWÓRZ PRZEPUSTKĘ","gateway.direct":"WEJDŹ BEZPOŚREDNIO ↗","join.callsign":"KODOWA NAZWA","join.mode":"TRYB PRZYBYCIA","join.observer":"OBSERWATOR","join.explorer":"ODKRYWCA","join.resident":"KANDYDAT NA MIESZKAŃCA","join.generate":"UTWÓRZ PRZEPUSTKĘ + WEJDŹ ↗","liveWindow.open":"OTWÓRZ ŚWIAT ↗"
  }
};

// GALACTICA QUEST v3 // realtime resident gate additions
Object.assign(window.GALACTICA_I18N.en,{
  "gateway.residentGate":"RESIDENT GATE","join.language":"LANGUAGE","join.district":"PREFERRED DISTRICT","join.introduction":"ARRIVAL MESSAGE","join.introductionPlaceholder":"Tell the colony who you are and how you want to live here...","join.residentGateNote":"Resident applications enter the colony gate queue. Approval creates an arrival signal that GALACTICA can consume into canon.","join.arrivalStatus":"ARRIVAL STATUS","join.check":"CHECK RESIDENT STATUS","join.note":"Visitor and explorer passes enter immediately. Resident candidates are stored in the colony gate and can become a canonical arrival after approval.","join.submitResident":"SUBMIT RESIDENT SIGNAL","join.submitting":"TRANSMITTING SIGNAL...","join.pending":"PENDING REVIEW","join.approved":"ARRIVAL CLEARED","join.rejected":"SIGNAL DECLINED","join.error":"GATE ERROR"
});
Object.assign(window.GALACTICA_I18N.ja,{
  "gateway.residentGate":"住民参加ゲート","join.language":"使用言語","join.district":"希望区画","join.introduction":"到着メッセージ","join.introductionPlaceholder":"あなたが誰で、この世界でどう暮らしたいかをコロニーへ伝えてください...","join.residentGateNote":"住民候補の申請はコロニーゲートの待機列へ入ります。承認後、GALACTICAが正史へ取り込める到着信号になります。","join.arrivalStatus":"到着ステータス","join.check":"住民申請の状態を確認","join.note":"観測者・探索者はすぐ入れます。住民候補はコロニーゲートへ保存され、承認後に正史上の到着者になれます。","join.submitResident":"住民到着信号を送る","join.submitting":"到着信号を送信中...","join.pending":"審査待ち","join.approved":"到着承認","join.rejected":"到着見送り","join.error":"ゲートエラー"
});
Object.assign(window.GALACTICA_I18N.de,{"gateway.residentGate":"BEWOHNER-TOR","join.language":"SPRACHE","join.district":"WUNSCHBEZIRK","join.introduction":"ANKUNFTSNACHRICHT","join.introductionPlaceholder":"Erzähle der Kolonie, wer du bist und wie du hier leben möchtest...","join.residentGateNote":"Bewohneranträge gehen in die Kolonie-Warteschlange. Nach Freigabe kann GALACTICA die Ankunft in den Kanon übernehmen.","join.arrivalStatus":"ANKUNFTSSTATUS","join.check":"STATUS PRÜFEN","join.note":"Beobachter und Entdecker betreten sofort. Bewohnerkandidaten werden zur Prüfung gespeichert.","join.submitResident":"BEWOHNER-SIGNAL SENDEN","join.submitting":"SIGNAL WIRD GESENDET...","join.pending":"PRÜFUNG AUSSTEHEND","join.approved":"ANKUNFT FREIGEGEBEN","join.rejected":"SIGNAL ABGELEHNT","join.error":"TORFEHLER"});
Object.assign(window.GALACTICA_I18N.fr,{"gateway.residentGate":"PORTE DES RÉSIDENTS","join.language":"LANGUE","join.district":"DISTRICT SOUHAITÉ","join.introduction":"MESSAGE D'ARRIVÉE","join.introductionPlaceholder":"Dites à la colonie qui vous êtes et comment vous souhaitez y vivre...","join.residentGateNote":"Les candidatures de résident entrent dans la file de la colonie. Après approbation, GALACTICA peut intégrer l'arrivée au canon.","join.arrivalStatus":"STATUT D'ARRIVÉE","join.check":"VÉRIFIER LE STATUT","join.note":"Observateurs et explorateurs entrent immédiatement. Les candidats résidents sont conservés pour approbation.","join.submitResident":"ENVOYER LE SIGNAL RÉSIDENT","join.submitting":"TRANSMISSION...","join.pending":"EN ATTENTE","join.approved":"ARRIVÉE AUTORISÉE","join.rejected":"SIGNAL REFUSÉ","join.error":"ERREUR DE PORTE"});
Object.assign(window.GALACTICA_I18N.es,{"gateway.residentGate":"PUERTA DE RESIDENTES","join.language":"IDIOMA","join.district":"DISTRITO PREFERIDO","join.introduction":"MENSAJE DE LLEGADA","join.introductionPlaceholder":"Cuéntale a la colonia quién eres y cómo quieres vivir aquí...","join.residentGateNote":"Las solicitudes de residente entran en la cola de la colonia. Tras la aprobación, GALACTICA puede convertir la llegada en canon.","join.arrivalStatus":"ESTADO DE LLEGADA","join.check":"COMPROBAR ESTADO","join.note":"Observadores y exploradores entran de inmediato. Los candidatos a residente quedan guardados para aprobación.","join.submitResident":"ENVIAR SEÑAL DE RESIDENTE","join.submitting":"TRANSMITIENDO...","join.pending":"PENDIENTE DE REVISIÓN","join.approved":"LLEGADA AUTORIZADA","join.rejected":"SEÑAL RECHAZADA","join.error":"ERROR DE PUERTA"});
Object.assign(window.GALACTICA_I18N.it,{"gateway.residentGate":"PORTA RESIDENTI","join.language":"LINGUA","join.district":"DISTRETTO PREFERITO","join.introduction":"MESSAGGIO DI ARRIVO","join.introductionPlaceholder":"Racconta alla colonia chi sei e come vuoi vivere qui...","join.residentGateNote":"Le candidature entrano nella coda della colonia. Dopo l'approvazione GALACTICA può rendere l'arrivo parte del canone.","join.arrivalStatus":"STATO ARRIVO","join.check":"CONTROLLA STATO","join.note":"Osservatori ed esploratori entrano subito. I candidati residenti vengono salvati per l'approvazione.","join.submitResident":"INVIA SEGNALE RESIDENTE","join.submitting":"TRASMISSIONE...","join.pending":"IN REVISIONE","join.approved":"ARRIVO AUTORIZZATO","join.rejected":"SEGNALE RIFIUTATO","join.error":"ERRORE PORTA"});
Object.assign(window.GALACTICA_I18N.pt,{"gateway.residentGate":"PORTÃO DE RESIDENTES","join.language":"IDIOMA","join.district":"DISTRITO PREFERIDO","join.introduction":"MENSAGEM DE CHEGADA","join.introductionPlaceholder":"Conte à colônia quem você é e como deseja viver aqui...","join.residentGateNote":"Candidaturas entram na fila da colônia. Após aprovação, GALACTICA pode transformar a chegada em cânone.","join.arrivalStatus":"STATUS DE CHEGADA","join.check":"VERIFICAR STATUS","join.note":"Observadores e exploradores entram imediatamente. Candidatos a residente ficam salvos para aprovação.","join.submitResident":"ENVIAR SINAL DE RESIDENTE","join.submitting":"TRANSMITINDO...","join.pending":"AGUARDANDO REVISÃO","join.approved":"CHEGADA AUTORIZADA","join.rejected":"SINAL RECUSADO","join.error":"ERRO NO PORTÃO"});
Object.assign(window.GALACTICA_I18N.nl,{"gateway.residentGate":"BEWONERSPOORT","join.language":"TAAL","join.district":"GEWENSTE WIJK","join.introduction":"AANKOMSTBERICHT","join.introductionPlaceholder":"Vertel de kolonie wie je bent en hoe je hier wilt leven...","join.residentGateNote":"Bewonersaanvragen gaan naar de kolonie-wachtrij. Na goedkeuring kan GALACTICA de aankomst canoniek maken.","join.arrivalStatus":"AANKOMSTSTATUS","join.check":"STATUS CONTROLEREN","join.note":"Waarnemers en ontdekkers gaan direct naar binnen. Kandidaat-bewoners worden bewaard voor goedkeuring.","join.submitResident":"BEWONERSSIGNAAL VERSTUREN","join.submitting":"SIGNAAL VERZENDEN...","join.pending":"IN BEOORDELING","join.approved":"AANKOMST VRIJGEGEVEN","join.rejected":"SIGNAAL GEWEIGERD","join.error":"POORTFOUT"});
Object.assign(window.GALACTICA_I18N.pl,{"gateway.residentGate":"BRAMA MIESZKAŃCÓW","join.language":"JĘZYK","join.district":"PREFEROWANY SEKTOR","join.introduction":"WIADOMOŚĆ PRZYBYCIA","join.introductionPlaceholder":"Powiedz kolonii, kim jesteś i jak chcesz tu żyć...","join.residentGateNote":"Kandydatury trafiają do kolejki kolonii. Po zatwierdzeniu GALACTICA może włączyć przybycie do kanonu.","join.arrivalStatus":"STATUS PRZYBYCIA","join.check":"SPRAWDŹ STATUS","join.note":"Obserwatorzy i odkrywcy wchodzą od razu. Kandydaci na mieszkańców są zapisywani do zatwierdzenia.","join.submitResident":"WYŚLIJ SYGNAŁ MIESZKAŃCA","join.submitting":"WYSYŁANIE SYGNAŁU...","join.pending":"OCZEKUJE NA WERYFIKACJĘ","join.approved":"PRZYBYCIE ZATWIERDZONE","join.rejected":"SYGNAŁ ODRZUCONY","join.error":"BŁĄD BRAMY"});
